<template>
  <span
    un-relative
    un-inline-flex
    un-isolate
    un-max-w="[calc(100vw-1rem)]"
  >
    <span
      aria-hidden="true"
      un-absolute
      un-inset-0
      un-z-0
      un-pointer-events-none
      un-bg-float
      un-border-b
      un-border-muted
      un-shadow="[0_0_12px_2px_var(--float-shadow),0_8px_20px_var(--float-shadow)]"
      un-backdrop-blur-sm
    />
    <span
      un-relative
      un-z-1
      un-inline-flex
      un-items-center
      un-gap-1
      un-px-2.5
      un-py-1
      un-text-base
    >
      <slot />
    </span>
  </span>
</template>
